### ISSUE TITLE
Update Parse SDK dependency

### ISSUE THREAD

**Issue by AlexBalo** [parse-community/ParseTwitterUtils-Android#14]
The sdk has been updated to version 1.11.0. Would it be possible to update the dependency for this project as well?

Thank you! :)

**Comment by grantland** [comment]
I've created a PR, but for now you can manually add `parse-android` as a dependency targeting the latest version:

``` java
dependencies {
    compile 'com.parse:parse-android:1.11.0'
    compile 'com.parse:parsetwitterutils-android:1.10.3`
}
```
