### ISSUE TITLE
Twitter login fails with TwitterUtils version 1.10.4

### ISSUE THREAD

**Issue by sichevoi** [parse-community/ParseTwitterUtils-Android#17]
We have updated twitter-utils library from version 1.10.3 to 1.10.4. Everything has been working fine with v. 1.10.3 but with 1.10.4 twitter login fails with the following exception:
`com.parse.internal.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Attempt to invoke interface method 'java.lang.Object com.parse.internal.signpost.http.HttpRequest.unwrap()' on a null object reference`

Here is a parse-starter-project with Twitter login enabled (see Login in the action bar). The current version would fail, when changing twitter-utils to 1.10.3 it works.
`git clone https://github.com/sichevoi/Parse-Starter-Project.git`

**Comment by grantland** [comment]
Could you post the entire stacktrace?

**Comment by grantland** [comment]
@sichevoi does this seem related? https://github.com/ParsePlatform/ParseUI-Android/issues/122

**Comment by sichevoi** [comment]
@grantland Yes, that is the same issue. I've tested with the suggested solution (`compile 'com.squareup.okhttp:okhttp-urlconnection:2.7.2'`) and it now works. Thanks! 
I'm closing this one. Maybe it makes sense to add a reference to this dependency into the Readme

**Comment by natario1** [comment]
@grantland 
There might still be something wrong in 1.10.5?

I’m not a twitter user so I personally don’t use this often, but weeks ago login was working smoothly. Now it asks for credentials and then, after a minute or so, calls done with the exception

```
ParseRequestException: i\o failure
cause: java.net.SocketTimeoutException: timeout
```

Adding the okhttp dependency clearly doesn’t solve.

**Comment by grantland** [comment]
From the error it looks like there's a connectivity issue, not an issue with the SDK.

**Comment by natario1** [comment]
@grantland I’m not 100% sure it is SDK related, just asking.

I can login with Facebook or use my app regularly. But ParseTwitterUtils.logIn() and ParseTwitterUtils.link() both won’t work anymore, and return the same exception.

I have also kept trying in the last 24hour, so it doesn’t look like a temporary issue.

**Comment by sichevoi** [comment]
We observed issues with Twitter login yesterday both on Android and iOS, so assumed that was some service issue. Just checked - works fine now.

**Comment by natario1** [comment]
@sichevoi 
You are right, thank you. I was unfortunate enough to ignore twitter for a month, then update dependencies, then come back on the exact day it wasn’t working.
