### ISSUE TITLE
Add support for OkHttp3

### ISSUE THREAD

**Issue by vjames19** [parse-community/ParseTwitterUtils-Android#21]
The HttpURLConnectionClient.java only search for the previous version of OkHttp: https://github.com/ParsePlatform/ParseTwitterUtils-Android/blob/e8e402dbaaeb78c16211905f659af174c14ee908/library/src/main/java/com/parse/internal/signpost/basic/HttpURLConnectionClient.java#L23

**Comment by Jawnnypoo** [comment]
It is the default now. Thanks!
