### ISSUE TITLE
Is there an safer way to do ParseTwitterUtils.initialize(TWITTER_KEY, TWITTER_SECRET)?

### ISSUE THREAD

**Issue by skywalkerlw** [parse-community/ParseTwitterUtils-Android#25]
I have to admit that strictly it's not a Parse special issue, but 
Since proguard does not obfuscate constant string, is there a safer way or recommended way to use rather than directly input  TWITTER_KEY and TWITTER_SECRET in ParseTwitterUtils.initialize(TWITTER_KEY, TWITTER_SECRET)?

**Comment by grantland** [comment]
OAuth keys and secrets are inherently public values so there shouldn't be a reason to need to obfuscate them.

**Comment by skywalkerlw** [comment]
However, since key/secret can be got by somebody else by decompiling, it could make a risk if they misuse this key/secret, don't you think so? For example, he can build a fake app,etc. 

Thanks

**Comment by grantland** [comment]
They would be forced to authorize users under your application's name and icon and would only be able to access Twitter data from those users, but not data from your Parse application.

In the end, these keys are meant to be public and security by obscurity isn't security.
