### ISSUE TITLE
Are there plans to update this project to support Parse-SDK-Andriod 1.15.x?

### ISSUE THREAD

**Issue by nicktmro** [parse-community/ParseTwitterUtils-Android#27]
Currently it seems that `com.parse:parsetwitterutils-android:1.10.5` only works with version Parse-SDK-Andriod 1.14.1

I'm seeing 
```
Error:Module 'com.parse:parsetwitterutils-android:1.10.5' depends on one or more Android Libraries but is a jar
``` 
when using `1.10.5` alongside `com.parse:parse-android:1.15.5`

Cheers...

**Comment by nicktmro** [comment]
FWIW, updating to `compile 'com.parse:parsetwitterutils-android:1.10.5@aar'` does seem to work.

**Comment by josuer** [comment]
I was able to compile my app with 'com.parse:parse-android:1.15.2'  but after that I get the same error you have. I mean 'com.parse:parse-android:1.15.3+' doesn't work, where you able to fix it?

**Comment by nicktmro** [comment]
@josuer I am using `compile 'com.parse:parsetwitterutils-android:1.10.5@aar'` as I mentioned above and it seems fine. I saw there was a recent commit that may fix your issue, but I haven't tried it.

**Comment by josuer** [comment]
@nicktmro Ok, updated and now it is working, thank you very much.

**Comment by rogerhu** [comment]
1.10.6 has been pushed to jCenter() that should have aar by default now.  Can you give it a try?  You shouldn't need `@aar` now.

**Comment by Jawnnypoo** [comment]
This lib uses the latest now.
