### ISSUE TITLE
Is the CLA still required to contribute PRs?

### ISSUE THREAD

**Issue by nicktmro** [parse-community/ParseTwitterUtils-Android#29]
Hi all, 

The [contributing.md](https://github.com/parse-community/ParseTwitterUtils-Android/blob/master/CONTRIBUTING.md) file mentions the need to submit a CLA (to Facebook) prior to the submission of the first Pull Request. Is this still a requirement or is the documentation simply outdated?

Cheers

**Comment by Jawnnypoo** [comment]
Thanks for noting this, it is updated now to the latest
