### ISSUE TITLE
Parse docs

### ISSUE THREAD

**Issue by Orbyt** [parse-community/ParseTwitterUtils-Android#3]
This lib isnt mentioned anywhere in the adding Twitter Users section in the Parse documentation. Should be added.

**Comment by grantland** [comment]
Feel free to add this, our docs are open source :smile: 

https://github.com/ParsePlatform/Docs

**Comment by Orbyt** [comment]
@grantland Done: https://github.com/ParsePlatform/Docs/pull/232
