### ISSUE TITLE
Failed Gradle build, DexException

### ISSUE THREAD

**Issue by Orbyt** [parse-community/ParseTwitterUtils-Android#4]
So im getting a DexException when trying to build.

`com.android.dex.DexException: Multiple dex files define Lcom/parse/AbstractQueryController$1;`

> Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_05\bin\java.exe'' finished with non-zero exit value 2

This happens when adding `compile 'com.parse:parsetwitterutils-android:1.10.3'` to my dependencies.

The only other lines in my build file related to Parse are:

```
    compile 'com.parse.bolts:bolts-android:1.+'
    compile fileTree(dir: 'libs', include: 'Parse-*.jar')
```

In my project directory external libs view, the only .jars i have relating to Parse are parse-android-1.10.2 and parsetwitterutils-android-1.10.3.

Ideas?

Update: If I remove the Parse.jar from the build path as well as `compile 'com.parse.bolts:bolts-android:1.+'` the project builds. So is this lib including those 2 components for some reason?

**Comment by grantland** [comment]
`parse-android` is a transitive dependency of `parsetwitterutils-android`, which will clash with `Parse-x.x.x.jar` that you have.

See here: http://search.maven.org/#artifactdetails%7Ccom.parse%7Cparsetwitterutils-android%7C1.10.3%7Cjar

**Comment by Orbyt** [comment]
@grantland Ok so if im understanding you correctly, the Parse-x.x.x.jar is not needed then, as its included when I include `parsetwitterutils-android`?

**Comment by grantland** [comment]
Correct. You may also add `parse-android` and it'll resolve correctly.

**Comment by Orbyt** [comment]
@grantland 

> Correct. You may also add parse-android and it'll resolve correctly.

So I added `compile 'com.parse:parse-android:1.10.3'`. Why does this not conflict if it pulls in the same info as the `.jar`? I'm also able to build without that line, and just using `compile 'com.parse:parsetwitterutils-android:1.10.3'` by itself.

**Comment by grantland** [comment]
When using Maven dependencies, it can de-duplicate using the version number which the `.jar` does not have.

It works without it since `parsetwitterutils-android` has it as a transitive dependency.

**Comment by Orbyt** [comment]
@grantland 

> It works without it since parsetwitterutils-android has it as a transitive dependency.

So again theres no point in adding it im assuming.

**Comment by grantland** [comment]
Not necessary, no.

**Comment by Orbyt** [comment]
@grantland 

Much appreciated.
