### ISSUE TITLE
PushService not recognized

### ISSUE THREAD

**Issue by assilMekki** [parse-community/ParseTwitterUtils-Android#40]
Hello, 

I just updated for version 1.11.1 to get the latest twitter callback fix, but after doing that 
<service android:name="com.parse.PushService" />
and 
<receiver android:name="com.parse.GcmBroadcastReceiver">

are not recognized anymore in my manifest, I honestly have no idea why is this happening but I am happy to provide any other details I can to help solve this.

Thank you.

**Comment by Jawnnypoo** [comment]
Hey there, sounds like your app was not updated to `1.17.x` of the Parse Android SDK. That involves migrating GCM push over to FCM, or potentially migrating over to the deprecated GCM module. Take a look at the README of the Parse Android SDK for more. https://github.com/parse-community/Parse-SDK-Android
