### ISSUE TITLE
Must Initialize Fabric before using singleton()

### ISSUE THREAD

**Issue by nagsrk** [parse-community/ParseTwitterUtils-Android#5]
ParseTwitterUtils.initialize("TWITTER_KEY", "TWITTER_SECRET") showing error "Must Initialize Fabric before using singleton()". 

If the app is using only Twitter without Parse, it can be done by 
TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);
Fabric.with(this, new Twitter(authConfig));

but how do we initialize with ParseTwitterUtils?

**Comment by grantland** [comment]
ParseTwitterUtils doesn't interact with Fabric at all, so this couldn't be happening. Could you post a full stacktrace of your error along with a concise sample project that reproduces this issue?
